# Generated by Django 2.2.5 on 2020-01-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cathegory', models.CharField(choices=[('Veggie', 'Veggie'), ('Made by Animal', 'From Animal'), ('Made of Animal', 'Made of Animal')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ingredients', models.ManyToManyField(to='appone.Ingredient')),
            ],
        ),
    ]
